version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/var/www/html
    depends_on: 
      - db
      - redis 
    command: symfony server:start --no-tls --port=8000 --allow-all-ip
    ports: 
      - "8080:8000"

  db:
    image: postgres:15.2-bullseye
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.6
    command: ["redis-server", "--save", "", "--appendonly", "no", "--loglevel", "warning"]
    ports:
      - "6379:6379"
