version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
