# config/services.yaml
services:
    _defaults:
        autowire: true      # Automatically inject dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Registre de controladors com a serveis públics
    App\Api\Controller\:
        resource: '../src/Api/Controller/*'
        public: true
        autowire: true
        autoconfigure: true


    # Automatically register all handlers
    App\Application\Command\Handler\:
        resource: '../src/Application/Command/Handler'
        tags: [ 'messenger.message_handler' , 'app.handler' ]
        autowire: true
        autoconfigure: false
        public: false

    App\Application\Query\Handler\:
        resource: '../src/Application/Query/Handler'
        tags: [ 'messenger.message_handler' , 'app.handler' ]
        autowire: true
        autoconfigure: false
        public: false

    # Make the CartRepository and other services available
    redis.client:
        class: Predis\Client
        arguments:
            - '%env(REDIS_URL)%'

    App\Infrastructure\Repository\RedisCartRepository:
        arguments:
            $redis: '@redis.client'

    App\Domain\Repository\CartRepositoryInterface: '@App\Infrastructure\Repository\RedisCartRepository'
